name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Intall deps
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist
        name: dist-files