name: Deploy React App
on: 
  push:
    branches:
      - master
    # paths-ignore:
    #   - '.githuib/workflows/*'   
jobs:
  test_my_app:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v4
        with: 
          path: '%LocalAppData%/npm-cache'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Test app
        run: npm run test 
  lint:
    runs-on: windows-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v4
        with: 
          path: '%LocalAppData%/npm-cache'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Lint app
        run: npm run lint    
  build:
    runs-on: windows-latest
    needs: [lint, test_my_app]
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v4
        with: 
          path: '%LocalAppData%/npm-cache'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Build app
        run: npm run build     
      - name: Deploy
        run: echo -n Deploing...
